//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to find the tab file or the grid file?.
        /// </summary>
        internal static string ASK_LOCATE_TAB_FILE_OR_GRID_FILE {
            get {
                return ResourceManager.GetString("ASK_LOCATE_TAB_FILE_OR_GRID_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to find the tab file or the raster file?.
        /// </summary>
        internal static string ASK_LOCATE_TAB_FILE_OR_RASTER_FILE {
            get {
                return ResourceManager.GetString("ASK_LOCATE_TAB_FILE_OR_RASTER_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on/off auto locking of windows\nAuto lock window.
        /// </summary>
        internal static string BTN_HLP_AUTOLOCK_WINDOWS {
            get {
                return ResourceManager.GetString("BTN_HLP_AUTOLOCK_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone active window\nClone window.
        /// </summary>
        internal static string BTN_HLP_CLONE_FRONT_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_CLONE_FRONT_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close active window\nClose window.
        /// </summary>
        internal static string BTN_HLP_CLOSE_FRONT_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_CLOSE_FRONT_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock active window from closing\nLock window.
        /// </summary>
        internal static string BTN_HLP_LOCK_FRONT_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_LOCK_FRONT_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore closed window\nRestore closed window.
        /// </summary>
        internal static string BTN_HLP_RESTORE_CLOSED_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_RESTORE_CLOSED_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set preferred size and position on front window\nSet preferred size and position.
        /// </summary>
        internal static string BTN_HLP_SET_WINDOW_SIZE_POSITION_USING_BASE_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_SET_WINDOW_SIZE_POSITION_USING_BASE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock active window from closing\nUnlock window.
        /// </summary>
        internal static string BTN_HLP_UNLOCK_FRONT_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_UNLOCK_FRONT_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base windows ({0}).
        /// </summary>
        internal static string DLG_BASE_WINDOW_X {
            get {
                return ResourceManager.GetString("DLG_BASE_WINDOW_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Functions and Subprocedures.
        /// </summary>
        internal static string DLG_LIST_FUNCTIONS_PROCEDURES {
            get {
                return ResourceManager.GetString("DLG_LIST_FUNCTIONS_PROCEDURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Window.
        /// </summary>
        internal static string DLG_MODIFY_WINDOW {
            get {
                return ResourceManager.GetString("DLG_MODIFY_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of bins has been limited to {0}..
        /// </summary>
        internal static string DLG_NUM_BINS_LIMITED_TO {
            get {
                return ResourceManager.GetString("DLG_NUM_BINS_LIMITED_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string DLG_OPTIONS {
            get {
                return ResourceManager.GetString("DLG_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste All Properties.
        /// </summary>
        internal static string DLG_PASTE_ALL {
            get {
                return ResourceManager.GetString("DLG_PASTE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Label Settings.
        /// </summary>
        internal static string DLG_PASTE_LABEL {
            get {
                return ResourceManager.GetString("DLG_PASTE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Label Overrides.
        /// </summary>
        internal static string DLG_PASTE_LABEL_OBERRIDES {
            get {
                return ResourceManager.GetString("DLG_PASTE_LABEL_OBERRIDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Layer Filters.
        /// </summary>
        internal static string DLG_PASTE_LAYER_FILTERS {
            get {
                return ResourceManager.GetString("DLG_PASTE_LAYER_FILTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Layer Styles.
        /// </summary>
        internal static string DLG_PASTE_LAYER_STYLES {
            get {
                return ResourceManager.GetString("DLG_PASTE_LAYER_STYLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Style Overrides.
        /// </summary>
        internal static string DLG_PASTE_STYLE_OVERRIDES {
            get {
                return ResourceManager.GetString("DLG_PASTE_STYLE_OVERRIDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Time Properties.
        /// </summary>
        internal static string DLG_PASTE_TIME_PROPERTIES {
            get {
                return ResourceManager.GetString("DLG_PASTE_TIME_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Theme.
        /// </summary>
        internal static string DLG_STATIC_THEME {
            get {
                return ResourceManager.GetString("DLG_STATIC_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Column with Categories.
        /// </summary>
        internal static string DLG_STATIC_THEME_SELECT_COLUMN {
            get {
                return ResourceManager.GetString("DLG_STATIC_THEME_SELECT_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Table for Theme.
        /// </summary>
        internal static string DLG_STATIC_THEME_SELECT_TABLE {
            get {
                return ResourceManager.GetString("DLG_STATIC_THEME_SELECT_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Bins.
        /// </summary>
        internal static string DLG_THEME_NUM_BINS {
            get {
                return ResourceManager.GetString("DLG_THEME_NUM_BINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Ranges.
        /// </summary>
        internal static string DLG_THEME_NUM_COLOR_RANGES {
            get {
                return ResourceManager.GetString("DLG_THEME_NUM_COLOR_RANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Color Range.
        /// </summary>
        internal static string DLG_THEME_SELECT_COLOR_RANGE {
            get {
                return ResourceManager.GetString("DLG_THEME_SELECT_COLOR_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Column for Thematic Map.
        /// </summary>
        internal static string DLG_THEME_SELECT_COLUMN {
            get {
                return ResourceManager.GetString("DLG_THEME_SELECT_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Layer for Thematic Map.
        /// </summary>
        internal static string DLG_THEME_SELECT_LAYER {
            get {
                return ResourceManager.GetString("DLG_THEME_SELECT_LAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Layer Rename.
        /// </summary>
        internal static string DLG_TITLE_ADVANCED_LAYER_RENAME {
            get {
                return ResourceManager.GetString("DLG_TITLE_ADVANCED_LAYER_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Multiple Layers.
        /// </summary>
        internal static string DLG_TITLE_MULTIPLE_LAYERS_RENAME {
            get {
                return ResourceManager.GetString("DLG_TITLE_MULTIPLE_LAYERS_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Individual Theme.
        /// </summary>
        internal static string DLG_TITLE_QUICK_THEME_INDIVIDUAL {
            get {
                return ResourceManager.GetString("DLG_TITLE_QUICK_THEME_INDIVIDUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Ranged Theme.
        /// </summary>
        internal static string DLG_TITLE_QUICK_THEME_RANGED {
            get {
                return ResourceManager.GetString("DLG_TITLE_QUICK_THEME_RANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Map Extent.
        /// </summary>
        internal static string DLG_TTL_CREATE_MAP_EXTENT {
            get {
                return ResourceManager.GetString("DLG_TTL_CREATE_MAP_EXTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Layer Properties.
        /// </summary>
        internal static string DLG_TTL_PASTE_LAYER_PROPERTIES {
            get {
                return ResourceManager.GetString("DLG_TTL_PASTE_LAYER_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore windows.
        /// </summary>
        internal static string DLG_TTL_RESTORE_WINDOWS {
            get {
                return ResourceManager.GetString("DLG_TTL_RESTORE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Map Extent of.
        /// </summary>
        internal static string DLG_TXT_CREATE_EXTENT_OF {
            get {
                return ResourceManager.GetString("DLG_TXT_CREATE_EXTENT_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Extent Style.
        /// </summary>
        internal static string DLG_TXT_EXTENT_STYLE {
            get {
                return ResourceManager.GetString("DLG_TXT_EXTENT_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick window to restore.
        /// </summary>
        internal static string DLG_TXT_PICK_WINDOW_TO_RESTORE {
            get {
                return ResourceManager.GetString("DLG_TXT_PICK_WINDOW_TO_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cosmetic layer is not supported!.
        /// </summary>
        internal static string ERR_COSMETIC_LAYER_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_COSMETIC_LAYER_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty string can not be used as the friendly name of a layer!.
        /// </summary>
        internal static string ERR_EMPTY_STRING_NOT_SUPPORTED_AS_FRIENDLY_NAME {
            get {
                return ResourceManager.GetString("ERR_EMPTY_STRING_NOT_SUPPORTED_AS_FRIENDLY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name of the new base window!.
        /// </summary>
        internal static string ERR_ENTER_NAME_FOR_NEW_BASE_WINDOW {
            get {
                return ResourceManager.GetString("ERR_ENTER_NAME_FOR_NEW_BASE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the window!.
        /// </summary>
        internal static string ERR_ENTER_NAME_FOR_WINDOW {
            get {
                return ResourceManager.GetString("ERR_ENTER_NAME_FOR_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a size larger than 0!.
        /// </summary>
        internal static string ERR_ENTER_SIZE_LARGER_THAN_0 {
            get {
                return ResourceManager.GetString("ERR_ENTER_SIZE_LARGER_THAN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The active window must be a mapper window!.
        /// </summary>
        internal static string ERR_FRONT_WIN_NOT_MAPPER {
            get {
                return ResourceManager.GetString("ERR_FRONT_WIN_NOT_MAPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML is invalid!.
        /// </summary>
        internal static string ERR_INVALID_XML {
            get {
                return ResourceManager.GetString("ERR_INVALID_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The must be at least one map window open!.
        /// </summary>
        internal static string ERR_NO_MAP_WIN_OPEN {
            get {
                return ResourceManager.GetString("ERR_NO_MAP_WIN_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click in the cell to read the value from! The application ignores the first row in the first column.
        /// </summary>
        internal static string ERR_NO_SELECT_SELECTED_TOP_LEFT_CELL_IGNORED {
            get {
                return ResourceManager.GetString("ERR_NO_SELECT_SELECTED_TOP_LEFT_CELL_IGNORED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map doesn&apos;t have a selectable layer.
        /// </summary>
        internal static string ERR_NO_SELECTABLE_LAYER {
            get {
                return ResourceManager.GetString("ERR_NO_SELECTABLE_LAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The must be at least one window open!.
        /// </summary>
        internal static string ERR_NO_WIN_OPEN {
            get {
                return ResourceManager.GetString("ERR_NO_WIN_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no windows to restore!.
        /// </summary>
        internal static string ERR_NO_WINDOWS_TO_RESTORE {
            get {
                return ResourceManager.GetString("ERR_NO_WINDOWS_TO_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only char and numeric columns are supported.
        /// </summary>
        internal static string ERR_ONLY_CHAR_AND_NUM_COLS_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_ONLY_CHAR_AND_NUM_COLS_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a window to read the size and position from!.
        /// </summary>
        internal static string ERR_OPEN_WINDOW_TO_READ_SIZE_POSITION {
            get {
                return ResourceManager.GetString("ERR_OPEN_WINDOW_TO_READ_SIZE_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a window to resize and reposition!.
        /// </summary>
        internal static string ERR_OPEN_WINDOW_TO_RESIZE_REPOSITION {
            get {
                return ResourceManager.GetString("ERR_OPEN_WINDOW_TO_RESIZE_REPOSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a window to save to a workspace!.
        /// </summary>
        internal static string ERR_OPEN_WINDOW_TO_SAVE_TO_WOR {
            get {
                return ResourceManager.GetString("ERR_OPEN_WINDOW_TO_SAVE_TO_WOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the base window to update!.
        /// </summary>
        internal static string ERR_SELECT_BASE_WINDOW_TO_UPDATE {
            get {
                return ResourceManager.GetString("ERR_SELECT_BASE_WINDOW_TO_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a table with at least one numeric column!.
        /// </summary>
        internal static string ERR_SELECT_LAYER_WITH_NUMERIC_COLUMN {
            get {
                return ResourceManager.GetString("ERR_SELECT_LAYER_WITH_NUMERIC_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a non temporal layer in the Layer Control! .
        /// </summary>
        internal static string ERR_SELECT_NON_TEMPORAL_LAYER_IN_LAYER_CONTROL {
            get {
                return ResourceManager.GetString("ERR_SELECT_NON_TEMPORAL_LAYER_IN_LAYER_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a normal layer!.
        /// </summary>
        internal static string ERR_SELECT_NORMAL_LAYER_IN_LAYER_CONTROL {
            get {
                return ResourceManager.GetString("ERR_SELECT_NORMAL_LAYER_IN_LAYER_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a normal or raster/grid layer!.
        /// </summary>
        internal static string ERR_SELECT_NORMAL_OR_RASTER_OR_GRID_LAYER_IN_LAYER_CONTROL {
            get {
                return ResourceManager.GetString("ERR_SELECT_NORMAL_OR_RASTER_OR_GRID_LAYER_IN_LAYER_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one layer in the Layer Control!.
        /// </summary>
        internal static string ERR_SELECT_ONE_LAYER_IN_LAYER_CONTROL {
            get {
                return ResourceManager.GetString("ERR_SELECT_ONE_LAYER_IN_LAYER_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a single layer in the layer control!.
        /// </summary>
        internal static string ERR_SELECT_ONE_LAYER_IN_LC {
            get {
                return ResourceManager.GetString("ERR_SELECT_ONE_LAYER_IN_LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one map in the Layer Control!.
        /// </summary>
        internal static string ERR_SELECT_ONE_MAP_IN_LAYER_CONTROL {
            get {
                return ResourceManager.GetString("ERR_SELECT_ONE_MAP_IN_LAYER_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one table in the TableList window!.
        /// </summary>
        internal static string ERR_SELECT_ONE_TABLE_IN_TABLE_LIST {
            get {
                return ResourceManager.GetString("ERR_SELECT_ONE_TABLE_IN_TABLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Selected Record has no Spatial Object!.
        /// </summary>
        internal static string ERR_SELECTION_HAS_NO_SPATIAL_OBJECT {
            get {
                return ResourceManager.GetString("ERR_SELECTION_HAS_NO_SPATIAL_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select at least one Record!.
        /// </summary>
        internal static string ERR_SELECTION_NO_RECORDS {
            get {
                return ResourceManager.GetString("ERR_SELECTION_NO_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select exactly one Record!.
        /// </summary>
        internal static string ERR_SELECTION_NOT_ONE_RECORD {
            get {
                return ResourceManager.GetString("ERR_SELECTION_NOT_ONE_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table holds object types not supported by this function {0}.
        /// </summary>
        internal static string ERR_UNSUPPORTED_OBJECT_TYPE {
            get {
                return ResourceManager.GetString("ERR_UNSUPPORTED_OBJECT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Closed Windows.
        /// </summary>
        internal static string LST_CLOSED_WINDOWS_ALL {
            get {
                return ResourceManager.GetString("LST_CLOSED_WINDOWS_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Browser Windows.
        /// </summary>
        internal static string LST_CLOSED_WINDOWS_BROWSERS {
            get {
                return ResourceManager.GetString("LST_CLOSED_WINDOWS_BROWSERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Layout Windows.
        /// </summary>
        internal static string LST_CLOSED_WINDOWS_LAYOUTS {
            get {
                return ResourceManager.GetString("LST_CLOSED_WINDOWS_LAYOUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Map Windows.
        /// </summary>
        internal static string LST_CLOSED_WINDOWS_MAPS {
            get {
                return ResourceManager.GetString("LST_CLOSED_WINDOWS_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Windows.
        /// </summary>
        internal static string LST_WINDOWS_ALL {
            get {
                return ResourceManager.GetString("LST_WINDOWS_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Windows.
        /// </summary>
        internal static string LST_WINDOWS_BROWSERS {
            get {
                return ResourceManager.GetString("LST_WINDOWS_BROWSERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Windows.
        /// </summary>
        internal static string LST_WINDOWS_LAYOUTS {
            get {
                return ResourceManager.GetString("LST_WINDOWS_LAYOUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend Designer Windows.
        /// </summary>
        internal static string LST_WINDOWS_LEGENDS {
            get {
                return ResourceManager.GetString("LST_WINDOWS_LEGENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Windows.
        /// </summary>
        internal static string LST_WINDOWS_MAPS {
            get {
                return ResourceManager.GetString("LST_WINDOWS_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Windows.
        /// </summary>
        internal static string LST_WINDOWS_SPECIAL {
            get {
                return ResourceManager.GetString("LST_WINDOWS_SPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About {0}....
        /// </summary>
        internal static string MNU_ABOUT_PROGRAM_X {
            get {
                return ResourceManager.GetString("MNU_ABOUT_PROGRAM_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartographic Scale.
        /// </summary>
        internal static string MNU_ADD_SMARTTEXT_CART_SCALE {
            get {
                return ResourceManager.GetString("MNU_ADD_SMARTTEXT_CART_SCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection Name.
        /// </summary>
        internal static string MNU_ADD_SMARTTEXT_COORSYS {
            get {
                return ResourceManager.GetString("MNU_ADD_SMARTTEXT_COORSYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Title.
        /// </summary>
        internal static string MNU_ADD_SMARTTEXT_MAP_TITLE {
            get {
                return ResourceManager.GetString("MNU_ADD_SMARTTEXT_MAP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Rename.
        /// </summary>
        internal static string MNU_ADVANCED_RENAME {
            get {
                return ResourceManager.GetString("MNU_ADVANCED_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autolock Windows.
        /// </summary>
        internal static string MNU_AUTOLOCK_WINDOWS {
            get {
                return ResourceManager.GetString("MNU_AUTOLOCK_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse in Floating Window.
        /// </summary>
        internal static string MNU_BROWSE_FLOATING_WIN {
            get {
                return ResourceManager.GetString("MNU_BROWSE_FLOATING_WIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Browser.
        /// </summary>
        internal static string MNU_BROWSER_FLOATING {
            get {
                return ResourceManager.GetString("MNU_BROWSER_FLOATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Map.
        /// </summary>
        internal static string MNU_CLONE_MAP {
            get {
                return ResourceManager.GetString("MNU_CLONE_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Table.
        /// </summary>
        internal static string MNU_CLOSE_TABLE {
            get {
                return ResourceManager.GetString("MNU_CLOSE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Layer Properties.
        /// </summary>
        internal static string MNU_COPY_LAYER_PROPERTIES {
            get {
                return ResourceManager.GetString("MNU_COPY_LAYER_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Extent.
        /// </summary>
        internal static string MNU_CREATE_MAP_EXTENT {
            get {
                return ResourceManager.GetString("MNU_CREATE_MAP_EXTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;End Program.
        /// </summary>
        internal static string MNU_END_PROGRAM {
            get {
                return ResourceManager.GetString("MNU_END_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Using Cell Value.
        /// </summary>
        internal static string MNU_FILTER_USING_CELL_VALUE {
            get {
                return ResourceManager.GetString("MNU_FILTER_USING_CELL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Value.
        /// </summary>
        internal static string MNU_FILTER_USING_CELL_VALUE_SHORT {
            get {
                return ResourceManager.GetString("MNU_FILTER_USING_CELL_VALUE_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By Current Column.
        /// </summary>
        internal static string MNU_GROUP_BY_CURRENT_COLUMN {
            get {
                return ResourceManager.GetString("MNU_GROUP_BY_CURRENT_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MNU_HELP {
            get {
                return ResourceManager.GetString("MNU_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will let you rename the selected layer and let you save the new name as the default name.
        /// </summary>
        internal static string MNU_HLP_ADVANCED_RENAME {
            get {
                return ResourceManager.GetString("MNU_HLP_ADVANCED_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autolock all windows.
        /// </summary>
        internal static string MNU_HLP_AUTOLOCK_ALL_WINDOWS {
            get {
                return ResourceManager.GetString("MNU_HLP_AUTOLOCK_ALL_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display and Manipulate data in a floating browser window.
        /// </summary>
        internal static string MNU_HLP_BROWSER_FLOATING {
            get {
                return ResourceManager.GetString("MNU_HLP_BROWSER_FLOATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone the selected Map Window.
        /// </summary>
        internal static string MNU_HLP_CLONE_MAP {
            get {
                return ResourceManager.GetString("MNU_HLP_CLONE_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone window.
        /// </summary>
        internal static string MNU_HLP_CLONE_WINDOW {
            get {
                return ResourceManager.GetString("MNU_HLP_CLONE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the selected table.
        /// </summary>
        internal static string MNU_HLP_CLOSE_TABLE {
            get {
                return ResourceManager.GetString("MNU_HLP_CLOSE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close window.
        /// </summary>
        internal static string MNU_HLP_CLOSE_WINDOW {
            get {
                return ResourceManager.GetString("MNU_HLP_CLOSE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy All Settings from Selected Layer.
        /// </summary>
        internal static string MNU_HLP_COPY_LAYER_PROPERTIES {
            get {
                return ResourceManager.GetString("MNU_HLP_COPY_LAYER_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Map Extent into a map or table..
        /// </summary>
        internal static string MNU_HLP_CREATE_MAP_EXTENT {
            get {
                return ResourceManager.GetString("MNU_HLP_CREATE_MAP_EXTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make window dockable.
        /// </summary>
        internal static string MNU_HLP_DOCK_WINDOW {
            get {
                return ResourceManager.GetString("MNU_HLP_DOCK_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will filter the browser using the value in the currently selected cell.
        /// </summary>
        internal static string MNU_HLP_FILTER_USING_CELL_VALUE {
            get {
                return ResourceManager.GetString("MNU_HLP_FILTER_USING_CELL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a Group By Query on the currently selected column..
        /// </summary>
        internal static string MNU_HLP_GROUP_BY_CURRENT_COLUMN {
            get {
                return ResourceManager.GetString("MNU_HLP_GROUP_BY_CURRENT_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a clone of the active layout.
        /// </summary>
        internal static string MNU_HLP_LAYOUT_CLONE_VIEW {
            get {
                return ResourceManager.GetString("MNU_HLP_LAYOUT_CLONE_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds a file in Windows Explorer related to the selected table.
        /// </summary>
        internal static string MNU_HLP_LOCATE_FILE_IN_EXPLORER {
            get {
                return ResourceManager.GetString("MNU_HLP_LOCATE_FILE_IN_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock window.
        /// </summary>
        internal static string MNU_HLP_LOCK_WINDOW {
            get {
                return ResourceManager.GetString("MNU_HLP_LOCK_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change size or title of window.
        /// </summary>
        internal static string MNU_HLP_MODIFY_WINDOW {
            get {
                return ResourceManager.GetString("MNU_HLP_MODIFY_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Title and Size of Active Window.
        /// </summary>
        internal static string MNU_HLP_MOFIFY_WINDOW {
            get {
                return ResourceManager.GetString("MNU_HLP_MOFIFY_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename all layers to match the tab file name.
        /// </summary>
        internal static string MNU_HLP_MULTIPLE_LAYERS_RENAME {
            get {
                return ResourceManager.GetString("MNU_HLP_MULTIPLE_LAYERS_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the selected tab file in.
        /// </summary>
        internal static string MNU_HLP_OPEN_TABFILE_IN_TEXT_EDITOR {
            get {
                return ResourceManager.GetString("MNU_HLP_OPEN_TABFILE_IN_TEXT_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan to the Selected Record in the Front Most Map.
        /// </summary>
        internal static string MNU_HLP_PAN_TO_SELECTION_FRONT_MAP {
            get {
                return ResourceManager.GetString("MNU_HLP_PAN_TO_SELECTION_FRONT_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Layer Settings onto Selected Layer.
        /// </summary>
        internal static string MNU_HLP_PASTE_LAYER_PROPERTIES {
            get {
                return ResourceManager.GetString("MNU_HLP_PASTE_LAYER_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Individual Thematic Map from the First Character Column.
        /// </summary>
        internal static string MNU_HLP_QUICK_THEME_INDIVIDUAL {
            get {
                return ResourceManager.GetString("MNU_HLP_QUICK_THEME_INDIVIDUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Ranged Thematic Map from the First Numeric Column.
        /// </summary>
        internal static string MNU_HLP_QUICK_THEME_RANGED {
            get {
                return ResourceManager.GetString("MNU_HLP_QUICK_THEME_RANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Application at the Pitney Bowes Community Download Page.
        /// </summary>
        internal static string MNU_HLP_RATE_APPLICATION {
            get {
                return ResourceManager.GetString("MNU_HLP_RATE_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore one or more windows closed during this session.
        /// </summary>
        internal static string MNU_HLP_RESTORE_CLOSED_WINDOWS {
            get {
                return ResourceManager.GetString("MNU_HLP_RESTORE_CLOSED_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore closed window.
        /// </summary>
        internal static string MNU_HLP_RESTORE_WINDOW {
            get {
                return ResourceManager.GetString("MNU_HLP_RESTORE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Window Positions To The Saved State.
        /// </summary>
        internal static string MNU_HLP_RESTORE_WINDOWS_NOW {
            get {
                return ResourceManager.GetString("MNU_HLP_RESTORE_WINDOWS_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the active window to a workspace without the &apos;Open Table ...&apos; statements.
        /// </summary>
        internal static string MNU_HLP_SAVE_WINDOW_TO_WOR {
            get {
                return ResourceManager.GetString("MNU_HLP_SAVE_WINDOW_TO_WOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default view on all layers in map.
        /// </summary>
        internal static string MNU_HLP_SET_DEFAULT_VIEW_ALL_LAYERS {
            get {
                return ResourceManager.GetString("MNU_HLP_SET_DEFAULT_VIEW_ALL_LAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default view on selected layer.
        /// </summary>
        internal static string MNU_HLP_SET_DEFAULT_VIEW_SINGLE_LAYER {
            get {
                return ResourceManager.GetString("MNU_HLP_SET_DEFAULT_VIEW_SINGLE_LAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup base windows with size and position.
        /// </summary>
        internal static string MNU_HLP_SETUP_BASE_WINDOWS {
            get {
                return ResourceManager.GetString("MNU_HLP_SETUP_BASE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show list of functions and subprocedures to use with the Exec() function.
        /// </summary>
        internal static string MNU_HLP_SHOW_MB_FUNCTION_LIST {
            get {
                return ResourceManager.GetString("MNU_HLP_SHOW_MB_FUNCTION_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify which windows automatically to store positions of.
        /// </summary>
        internal static string MNU_HLP_STORE_WINDOW_POSITIONS {
            get {
                return ResourceManager.GetString("MNU_HLP_STORE_WINDOW_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store the current position of the windows.
        /// </summary>
        internal static string MNU_HLP_STORE_WINDOWS_NOW {
            get {
                return ResourceManager.GetString("MNU_HLP_STORE_WINDOWS_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore window positions when the program starts.
        /// </summary>
        internal static string MNU_HLP_TOGGLE_RESTORE_WINDOWS_ON_START {
            get {
                return ResourceManager.GetString("MNU_HLP_TOGGLE_RESTORE_WINDOWS_ON_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically show the Layer Control window on startup.
        /// </summary>
        internal static string MNU_HLP_TOGGLE_SHOW_LAYER_CONTROL {
            get {
                return ResourceManager.GetString("MNU_HLP_TOGGLE_SHOW_LAYER_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically show the TableList window on startup.
        /// </summary>
        internal static string MNU_HLP_TOGGLE_SHOW_TABLE_LIST {
            get {
                return ResourceManager.GetString("MNU_HLP_TOGGLE_SHOW_TABLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store window positions when the program ends.
        /// </summary>
        internal static string MNU_HLP_TOGGLE_STORE_WINDOWS_ON_EXIT {
            get {
                return ResourceManager.GetString("MNU_HLP_TOGGLE_STORE_WINDOWS_ON_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock window.
        /// </summary>
        internal static string MNU_HLP_UNLOCK_WINDOW {
            get {
                return ResourceManager.GetString("MNU_HLP_UNLOCK_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zooms to the entire view of the layers map.
        /// </summary>
        internal static string MNU_HLP_VIEW_ENTIRE_MAP {
            get {
                return ResourceManager.GetString("MNU_HLP_VIEW_ENTIRE_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to First.
        /// </summary>
        internal static string MNU_HLP_ZOOM_TO_FIRST {
            get {
                return ResourceManager.GetString("MNU_HLP_ZOOM_TO_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Last.
        /// </summary>
        internal static string MNU_HLP_ZOOM_TO_LAST {
            get {
                return ResourceManager.GetString("MNU_HLP_ZOOM_TO_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Next.
        /// </summary>
        internal static string MNU_HLP_ZOOM_TO_NEXT {
            get {
                return ResourceManager.GetString("MNU_HLP_ZOOM_TO_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Previous.
        /// </summary>
        internal static string MNU_HLP_ZOOM_TO_PREVIOUS {
            get {
                return ResourceManager.GetString("MNU_HLP_ZOOM_TO_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to the Extent of the Selection in the Front Most Map.
        /// </summary>
        internal static string MNU_HLP_ZOOM_TO_SELECTION_FRONT_MAP {
            get {
                return ResourceManager.GetString("MNU_HLP_ZOOM_TO_SELECTION_FRONT_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone View.
        /// </summary>
        internal static string MNU_LAYOUT_CLONE_VIEW {
            get {
                return ResourceManager.GetString("MNU_LAYOUT_CLONE_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate File In Windows Explorer.
        /// </summary>
        internal static string MNU_LOCATE_FILE_IN_EXPLORER {
            get {
                return ResourceManager.GetString("MNU_LOCATE_FILE_IN_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock window.
        /// </summary>
        internal static string MNU_LOCK_WINDOW {
            get {
                return ResourceManager.GetString("MNU_LOCK_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Window.
        /// </summary>
        internal static string MNU_MODIFY_WINDOW {
            get {
                return ResourceManager.GetString("MNU_MODIFY_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Multiple Layers.
        /// </summary>
        internal static string MNU_MULTIPLE_LAYERS_RENAME {
            get {
                return ResourceManager.GetString("MNU_MULTIPLE_LAYERS_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tab File In.
        /// </summary>
        internal static string MNU_OPEN_TABFILE_IN_TEXT_EDITOR {
            get {
                return ResourceManager.GetString("MNU_OPEN_TABFILE_IN_TEXT_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string MNU_OPTIONS {
            get {
                return ResourceManager.GetString("MNU_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan to the Selected Record.
        /// </summary>
        internal static string MNU_PAN_TO_SELECTION_FRONT_MAP {
            get {
                return ResourceManager.GetString("MNU_PAN_TO_SELECTION_FRONT_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Layer Properties.
        /// </summary>
        internal static string MNU_PASTE_LAYER_PROPERTIES {
            get {
                return ResourceManager.GetString("MNU_PASTE_LAYER_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Individual Theme.
        /// </summary>
        internal static string MNU_QUICK_THEME_INDIVIDUAL {
            get {
                return ResourceManager.GetString("MNU_QUICK_THEME_INDIVIDUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Ranged Theme.
        /// </summary>
        internal static string MNU_QUICK_THEME_RANGED {
            get {
                return ResourceManager.GetString("MNU_QUICK_THEME_RANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Application.
        /// </summary>
        internal static string MNU_RATE_APPLICATION {
            get {
                return ResourceManager.GetString("MNU_RATE_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Windows.
        /// </summary>
        internal static string MNU_RESTORE_CLOSED_WINDOWS {
            get {
                return ResourceManager.GetString("MNU_RESTORE_CLOSED_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Window Positions Now.
        /// </summary>
        internal static string MNU_RESTORE_WINDOWS_NOW {
            get {
                return ResourceManager.GetString("MNU_RESTORE_WINDOWS_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save To Workspace.
        /// </summary>
        internal static string MNU_SAVE_WINDOW_TO_WOR {
            get {
                return ResourceManager.GetString("MNU_SAVE_WINDOW_TO_WOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Extent Selection.
        /// </summary>
        internal static string MNU_SELECT_WITHIN_MAP {
            get {
                return ResourceManager.GetString("MNU_SELECT_WITHIN_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default View On All Layers.
        /// </summary>
        internal static string MNU_SET_DEFAULT_VIEW_ALL_LAYERS {
            get {
                return ResourceManager.GetString("MNU_SET_DEFAULT_VIEW_ALL_LAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default View.
        /// </summary>
        internal static string MNU_SET_DEFAULT_VIEW_SINGLE_LAYER {
            get {
                return ResourceManager.GetString("MNU_SET_DEFAULT_VIEW_SINGLE_LAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Rreferred Size And Position On Front Window.
        /// </summary>
        internal static string MNU_SET_WINDOW_SIZE_POSITION_USING_BASE_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SET_WINDOW_SIZE_POSITION_USING_BASE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Base Windows....
        /// </summary>
        internal static string MNU_SETUP_BASE_WINDOWS {
            get {
                return ResourceManager.GetString("MNU_SETUP_BASE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;All Windows.
        /// </summary>
        internal static string MNU_SHOW_ALL_WINDOWS {
            get {
                return ResourceManager.GetString("MNU_SHOW_ALL_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show The &amp;Info Window.
        /// </summary>
        internal static string MNU_SHOW_INFO_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_INFO_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show The &amp;Legend Window.
        /// </summary>
        internal static string MNU_SHOW_LEGEND_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_LEGEND_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show The Map&amp;Basic Window.
        /// </summary>
        internal static string MNU_SHOW_MAPBASIC_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_MAPBASIC_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show list of functions and subprocedures.
        /// </summary>
        internal static string MNU_SHOW_MB_FUNCTION_LIST {
            get {
                return ResourceManager.GetString("MNU_SHOW_MB_FUNCTION_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show The &amp;Message Window.
        /// </summary>
        internal static string MNU_SHOW_MESSAGE_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_MESSAGE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show The &amp;Ruler Window.
        /// </summary>
        internal static string MNU_SHOW_RULER_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_RULER_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show The &amp;Statistics Window.
        /// </summary>
        internal static string MNU_SHOW_STATISTICS_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_STATISTICS_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Show Window.
        /// </summary>
        internal static string MNU_SHOW_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Theme.
        /// </summary>
        internal static string MNU_STATIC_THEME {
            get {
                return ResourceManager.GetString("MNU_STATIC_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Auto Store Position Of Windows.
        /// </summary>
        internal static string MNU_STORE_WINDOW_POSITIONS {
            get {
                return ResourceManager.GetString("MNU_STORE_WINDOW_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Window Positions Now.
        /// </summary>
        internal static string MNU_STORE_WINDOWS_NOW {
            get {
                return ResourceManager.GetString("MNU_STORE_WINDOWS_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Window Positions On Startup.
        /// </summary>
        internal static string MNU_TOGGLE_RESTORE_WINDOWS_ON_START {
            get {
                return ResourceManager.GetString("MNU_TOGGLE_RESTORE_WINDOWS_ON_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Layer Control On Startup.
        /// </summary>
        internal static string MNU_TOGGLE_SHOW_LAYER_CONTROL {
            get {
                return ResourceManager.GetString("MNU_TOGGLE_SHOW_LAYER_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;TableList On Startup.
        /// </summary>
        internal static string MNU_TOGGLE_SHOW_TABLE_LIST {
            get {
                return ResourceManager.GetString("MNU_TOGGLE_SHOW_TABLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Window Positions On Exit.
        /// </summary>
        internal static string MNU_TOGGLE_STORE_WINDOWS_ON_EXIT {
            get {
                return ResourceManager.GetString("MNU_TOGGLE_STORE_WINDOWS_ON_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock window.
        /// </summary>
        internal static string MNU_UNLOCK_WINDOW {
            get {
                return ResourceManager.GetString("MNU_UNLOCK_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Entire Map.
        /// </summary>
        internal static string MNU_VIEW_ENTIRE_MAP {
            get {
                return ResourceManager.GetString("MNU_VIEW_ENTIRE_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Extent of Selection.
        /// </summary>
        internal static string MNU_ZOOM_TO_SELECTION_FRONT_MAP {
            get {
                return ResourceManager.GetString("MNU_ZOOM_TO_SELECTION_FRONT_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select workspace to save window to....
        /// </summary>
        internal static string PICK_WOR_TO_SAVE_WINDOW_TO {
            get {
                return ResourceManager.GetString("PICK_WOR_TO_SAVE_WINDOW_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowHelper can store size and position of windows on exit and restore these windows when it starts up next time. {\n}{\n}Do you want to turn this on?.
        /// </summary>
        internal static string QUEST_AUTOSTORE_WINDOW_POSITIONS {
            get {
                return ResourceManager.GetString("QUEST_AUTOSTORE_WINDOW_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to close this window: {0} ?.
        /// </summary>
        internal static string QUEST_CLOSE_WINDOW {
            get {
                return ResourceManager.GetString("QUEST_CLOSE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application extents MapInfo Pro with a number of useful features for working with windows.
        /// </summary>
        internal static string STR_APPLICATION_DESCRIPTION {
            get {
                return ResourceManager.GetString("STR_APPLICATION_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string STR_APPLY {
            get {
                return ResourceManager.GetString("STR_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Info.
        /// </summary>
        internal static string STR_BTN_SEL_INFO_HANDLER {
            get {
                return ResourceManager.GetString("STR_BTN_SEL_INFO_HANDLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string STR_CHANGE {
            get {
                return ResourceManager.GetString("STR_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string STR_CLOSE {
            get {
                return ResourceManager.GetString("STR_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window.
        /// </summary>
        internal static string STR_CLOSE_WINDOW {
            get {
                return ResourceManager.GetString("STR_CLOSE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string STR_COPY {
            get {
                return ResourceManager.GetString("STR_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmetic layer in.
        /// </summary>
        internal static string STR_COSM_LAYER_IN {
            get {
                return ResourceManager.GetString("STR_COSM_LAYER_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string STR_CREATE {
            get {
                return ResourceManager.GetString("STR_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable Layer in.
        /// </summary>
        internal static string STR_EDIT_LAYER_IN {
            get {
                return ResourceManager.GetString("STR_EDIT_LAYER_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exec() Expression copied to Clipboard: .
        /// </summary>
        internal static string STR_EXPRESSION_COPIED_TO_CLIPBOARD {
            get {
                return ResourceManager.GetString("STR_EXPRESSION_COPIED_TO_CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string STR_FILTER {
            get {
                return ResourceManager.GetString("STR_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Name.
        /// </summary>
        internal static string STR_FRIENDLY_LAYER_NAME {
            get {
                return ResourceManager.GetString("STR_FRIENDLY_LAYER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions and Subprocedures.
        /// </summary>
        internal static string STR_FUNCTIONS_SUBPROCEDURES {
            get {
                return ResourceManager.GetString("STR_FUNCTIONS_SUBPROCEDURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid File.
        /// </summary>
        internal static string STR_GRID_FILE {
            get {
                return ResourceManager.GetString("STR_GRID_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string STR_HEIGHT {
            get {
                return ResourceManager.GetString("STR_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Base Map Controls.
        /// </summary>
        internal static string STR_HIDE_BASE_MAP_CONTROL {
            get {
                return ResourceManager.GetString("STR_HIDE_BASE_MAP_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string STR_MAP {
            get {
                return ResourceManager.GetString("STR_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Mini Toolbar.
        /// </summary>
        internal static string STR_MAP_MINI_TOOLBAR {
            get {
                return ResourceManager.GetString("STR_MAP_MINI_TOOLBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Info Tool to Map Mini Toolbar.
        /// </summary>
        internal static string STR_MTB_ADD_INFO_TOOL {
            get {
                return ResourceManager.GetString("STR_MTB_ADD_INFO_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Ruler Tool to Map Mini Toolbar.
        /// </summary>
        internal static string STR_MTB_ADD_RULER_TOOL {
            get {
                return ResourceManager.GetString("STR_MTB_ADD_RULER_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string STR_NAME {
            get {
                return ResourceManager.GetString("STR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New base window.
        /// </summary>
        internal static string STR_NEW_BASE_WINDOW {
            get {
                return ResourceManager.GetString("STR_NEW_BASE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string STR_NO {
            get {
                return ResourceManager.GetString("STR_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string STR_OK {
            get {
                return ResourceManager.GetString("STR_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string STR_OPEN {
            get {
                return ResourceManager.GetString("STR_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string STR_POSITION {
            get {
                return ResourceManager.GetString("STR_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raster File.
        /// </summary>
        internal static string STR_RASTER_FILE {
            get {
                return ResourceManager.GetString("STR_RASTER_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename this table/layer in all map windows.
        /// </summary>
        internal static string STR_RENAME_LAYER_IN_ALL_MAPS {
            get {
                return ResourceManager.GetString("STR_RENAME_LAYER_IN_ALL_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string STR_RESTORE {
            get {
                return ResourceManager.GetString("STR_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as default friendly name.
        /// </summary>
        internal static string STR_SAVE_AS_DEFAULT_FRIENDLY_LAYER_NAME {
            get {
                return ResourceManager.GetString("STR_SAVE_AS_DEFAULT_FRIENDLY_LAYER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected records: {0}.
        /// </summary>
        internal static string STR_SELECTED_RECORDS_X {
            get {
                return ResourceManager.GetString("STR_SELECTED_RECORDS_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected records: {0} of {1}.
        /// </summary>
        internal static string STR_SELECTED_RECORDS_X_OF_Y {
            get {
                return ResourceManager.GetString("STR_SELECTED_RECORDS_X_OF_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Info when Deselecting Records.
        /// </summary>
        internal static string STR_SHOW_INFO_ON_DESELECT {
            get {
                return ResourceManager.GetString("STR_SHOW_INFO_ON_DESELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Info on Selection.
        /// </summary>
        internal static string STR_SHOW_INFO_ON_SELECTION {
            get {
                return ResourceManager.GetString("STR_SHOW_INFO_ON_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Layer with Friendly Name.
        /// </summary>
        internal static string STR_SKIP_LAYER_WITH_FRIENLY_NAME {
            get {
                return ResourceManager.GetString("STR_SKIP_LAYER_WITH_FRIENLY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Text Font.
        /// </summary>
        internal static string STR_SMART_TEXT_FONT {
            get {
                return ResourceManager.GetString("STR_SMART_TEXT_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab File.
        /// </summary>
        internal static string STR_TAB_FILE {
            get {
                return ResourceManager.GetString("STR_TAB_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string STR_TABLE {
            get {
                return ResourceManager.GetString("STR_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info on Selection is Disabled. Click to Enable Info on Selection.
        /// </summary>
        internal static string STR_TTIP_DISABLE_INFO_SEL {
            get {
                return ResourceManager.GetString("STR_TTIP_DISABLE_INFO_SEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info on Selection is Enabled. Click to Disable Info on Selection.
        /// </summary>
        internal static string STR_TTIP_ENABLE_INFO_SEL {
            get {
                return ResourceManager.GetString("STR_TTIP_ENABLE_INFO_SEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display tabular Information about map objects.
        /// </summary>
        internal static string STR_TTIP_INFO_TOOL {
            get {
                return ResourceManager.GetString("STR_TTIP_INFO_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the distance between two map points.
        /// </summary>
        internal static string STR_TTIP_RULER_TOOL {
            get {
                return ResourceManager.GetString("STR_TTIP_RULER_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string STR_UPDATE {
            get {
                return ResourceManager.GetString("STR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default Window Name.
        /// </summary>
        internal static string STR_USE_DEFAULT_WINDOW_NAME {
            get {
                return ResourceManager.GetString("STR_USE_DEFAULT_WINDOW_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Existing Table Description.
        /// </summary>
        internal static string STR_USE_EXISTING_TABLE_DESCRIPTION {
            get {
                return ResourceManager.GetString("STR_USE_EXISTING_TABLE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use File Name as Friendly Layer Name.
        /// </summary>
        internal static string STR_USE_FILENAME_AS_FRIENDLY_NAME {
            get {
                return ResourceManager.GetString("STR_USE_FILENAME_AS_FRIENDLY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string STR_WIDTH {
            get {
                return ResourceManager.GetString("STR_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Title.
        /// </summary>
        internal static string STR_WINDOW_NAME {
            get {
                return ResourceManager.GetString("STR_WINDOW_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string STR_X {
            get {
                return ResourceManager.GetString("STR_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string STR_Y {
            get {
                return ResourceManager.GetString("STR_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string STR_YES {
            get {
                return ResourceManager.GetString("STR_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string TAB_CLOSED {
            get {
                return ResourceManager.GetString("TAB_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string TAB_CURRENT {
            get {
                return ResourceManager.GetString("TAB_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string TAB_SPECIAL {
            get {
                return ResourceManager.GetString("TAB_SPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Smart Text for Cartographic Scale to the Map.
        /// </summary>
        internal static string TTIP_ADD_SMARTTEXT_CART_SCALE {
            get {
                return ResourceManager.GetString("TTIP_ADD_SMARTTEXT_CART_SCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Smart Text for Projection Name to the Map.
        /// </summary>
        internal static string TTIP_ADD_SMARTTEXT_COORSYS {
            get {
                return ResourceManager.GetString("TTIP_ADD_SMARTTEXT_COORSYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Smart Text for Map Title to the Map.
        /// </summary>
        internal static string TTIP_ADD_SMARTTEXT_MAPTITLE {
            get {
                return ResourceManager.GetString("TTIP_ADD_SMARTTEXT_MAPTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows are not automatically locked which would prevent them from being closed. Click here to enable automatically locking of windows.
        /// </summary>
        internal static string TTIP_AUTOLOCK_WINDOWS_OFF {
            get {
                return ResourceManager.GetString("TTIP_AUTOLOCK_WINDOWS_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows are automatically locked which prevents them  from being closed. Click here to disable automatically locking of windows.
        /// </summary>
        internal static string TTIP_AUTOLOCK_WINDOWS_ON {
            get {
                return ResourceManager.GetString("TTIP_AUTOLOCK_WINDOWS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock the window to prevent it from being closed.
        /// </summary>
        internal static string TTIP_LOCK_WINDOW {
            get {
                return ResourceManager.GetString("TTIP_LOCK_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Title and Size of Active Window.
        /// </summary>
        internal static string TTIP_MODIFY_WINDOW {
            get {
                return ResourceManager.GetString("TTIP_MODIFY_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This control isn&apos;t enabled until you have a window open.
        /// </summary>
        internal static string TTIP_MODIFY_WINDOW_DISABLED {
            get {
                return ResourceManager.GetString("TTIP_MODIFY_WINDOW_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate a Map Window to enable this feature..
        /// </summary>
        internal static string TTIP_NO_MAPPER_DISABLED {
            get {
                return ResourceManager.GetString("TTIP_NO_MAPPER_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Options dialog for the WindowHelper application.
        /// </summary>
        internal static string TTIP_OPTIONS {
            get {
                return ResourceManager.GetString("TTIP_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore windows that have been closed during this session.
        /// </summary>
        internal static string TTIP_RESTORE_CLOSED_WINDOWS {
            get {
                return ResourceManager.GetString("TTIP_RESTORE_CLOSED_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select objects that have their centroid within the current map extent.
        /// </summary>
        internal static string TTIP_SELECT_WITHIN_MAP {
            get {
                return ResourceManager.GetString("TTIP_SELECT_WITHIN_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Theme from a Column and the Existing Object Styles.
        /// </summary>
        internal static string TTIP_STATIC_THEME {
            get {
                return ResourceManager.GetString("TTIP_STATIC_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock the window to make it possible to close the window.
        /// </summary>
        internal static string TTIP_UNLOCK_WINDOW {
            get {
                return ResourceManager.GetString("TTIP_UNLOCK_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string VIEW_OF_VIEWS {
            get {
                return ResourceManager.GetString("VIEW_OF_VIEWS", resourceCulture);
            }
        }
    }
}
